name: Example workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Testes Unitarios
      run: |
        pip install pytest
        pytest
    - name: BDD
      run: |
        pip install behave
        behave
